import { useState, useRef, useEffect, useCallback } from 'react';
import { sendMessage, streamMessage, extractText, fetchAgentCard } from '../services/a2aClient';

// Generate contextual simulated responses based on agent capabilities and framework
function getSimulatedReply(agent, message) {
  const caps = (agent.capabilities || []).map((c) => c.toLowerCase());
  const name = (agent.name || '').toLowerCase();
  const fw = (agent.framework || '').toLowerCase();
  const msg = message.toLowerCase();

  // Capability-based response pools
  const responsesByCapability = {
    code: [
      `Here's the generated code based on your request:\n\n\`\`\`python\ndef solve(input):\n    # Implementation generated by ${agent.name}\n    result = process(input)\n    return result\n\`\`\`\n\nWant me to refine this or generate tests?`,
      `I've analyzed your requirements and generated a solution. The code uses modern patterns and includes error handling. Shall I walk you through the implementation?`,
      `Done! I've created the code artifact with full type annotations and documentation. You can find the output file in the streaming results.`,
    ],
    currency: [
      `Based on current exchange rates:\n\n💱 **100 USD → 91.25 EUR**\n💱 **100 USD → 12,450 JPY**\n\nRates are sourced in real-time. Want to convert a different amount?`,
      `I've completed the currency conversion. The exchange rate was last updated moments ago. Would you like to see historical trends?`,
    ],
    weather: [
      `🌤️ **Current conditions:**\n- Temperature: 72°F (22°C)\n- Humidity: 45%\n- Wind: 8 mph NW\n- Forecast: Partly cloudy, clearing by evening\n\nWant a multi-day forecast?`,
      `Here's the weather data I retrieved. Conditions look favorable for outdoor activities. Shall I check another location?`,
    ],
    travel: [
      `✈️ Here's your suggested itinerary:\n\n**Day 1:** Arrive, check in, explore local area\n**Day 2:** Guided tour of top attractions\n**Day 3:** Free day — local cuisine & markets\n**Day 4:** Adventure activity or cultural visit\n**Day 5:** Departure\n\nWant me to adjust the plan or add accommodation suggestions?`,
      `I've researched the destination and compiled recommendations for flights, hotels, and activities. Shall I refine any part of the itinerary?`,
    ],
    image: [
      `🎨 I've generated the image based on your description. The output has been sent as a **PNG artifact** through the A2A protocol. Would you like variations or adjustments?`,
      `Image generation complete! I used the CrewAI pipeline to produce a high-quality result matching your prompt. Want me to try a different style?`,
    ],
    content: [
      `📝 Here's the polished version of your content:\n\nI've improved clarity, fixed grammatical issues, and tightened the prose while preserving your voice. The key changes include stronger opening hooks and more concise paragraphs.\n\nWant me to adjust the tone or focus on a specific section?`,
      `I've reviewed and edited the content. Readability improved by ~30%. Shall I do another pass focusing on SEO optimization?`,
    ],
    data: [
      `📊 Analysis complete! Here are the key findings:\n\n- **Trend:** Revenue up 12% QoQ\n- **Anomaly:** Spike detected on March 5\n- **Correlation:** Strong link between feature usage and retention\n\nWant me to generate a detailed visualization?`,
      `I've queried the data and produced a summary. The results indicate a clear pattern worth investigating further. Shall I drill deeper?`,
    ],
    movie: [
      `🎬 Here's what I found:\n\n**The Shawshank Redemption** (1994)\n⭐ 9.3/10 — Drama\nDirected by Frank Darabont\nStarring Tim Robbins, Morgan Freeman\n\nA banker sentenced to life in prison forms an unlikely friendship and finds redemption.\n\nWant to know about the cast or similar movies?`,
      `I searched TMDB for your query and found several matching results. Want me to narrow down by genre, year, or actor?`,
    ],
    security: [
      `🔐 Security check complete. Authentication tokens verified and message signatures validated. All A2A protocol handshakes passed. Want me to run an audit on the full communication chain?`,
      `I've verified the bearer token against the Keycloak identity provider. Access is authorized. Shall I demonstrate the signing/verification flow?`,
    ],
    game: [
      `🔢 I'm thinking of a number between 1 and 100... Make your guess! I'll tell you if it's higher or lower. This demonstrates multi-turn A2A conversations.`,
      `🎲 Rolled a **d20** and got: **17**! Is that prime? Yes! Want me to roll again or try a different die?`,
    ],
    file: [
      `📄 I've parsed the uploaded file and indexed its contents. You can now ask me questions about the document and I'll use the parsed content as context for my responses. What would you like to know?`,
      `File processed successfully! I extracted 2,340 tokens of content. The document appears to be a technical specification. What questions do you have about it?`,
    ],
    github: [
      `🐙 I've fetched the repository details:\n\n- **Open issues:** 12\n- **Open PRs:** 3\n- **Latest commit:** "feat: add streaming support" (2h ago)\n\nWant me to create an issue, review a PR, or check CI status?`,
      `Repository scan complete. I found 3 PRs needing review and 5 issues labeled as high-priority. Shall I summarize them?`,
    ],
  };

  // Match agent capabilities/name/framework to response pools
  const matchedPools = [];
  for (const [key, pool] of Object.entries(responsesByCapability)) {
    const keyWords = key.split('|');
    if (
      keyWords.some((kw) => caps.some((c) => c.includes(kw))) ||
      keyWords.some((kw) => name.includes(kw)) ||
      keyWords.some((kw) => msg.includes(kw))
    ) {
      matchedPools.push(...pool);
    }
  }

  // Framework-specific responses as another layer
  if (fw && matchedPools.length === 0) {
    matchedPools.push(
      `I've processed your request using the **${agent.framework}** framework. Here are the results based on my analysis of your input. Want me to elaborate on any part?`,
      `Using **${agent.framework}**, I've completed the task. The A2A protocol streamed the results in real-time. Anything else you'd like me to do?`,
      `Task complete! I leveraged **${agent.framework}** to handle your request efficiently. The response was delivered via the A2A protocol. Need any adjustments?`,
    );
  }

  // Generic fallback for truly unknown agents
  if (matchedPools.length === 0) {
    matchedPools.push(
      `I've processed your request and here's what I found. As an A2A agent, I can handle follow-up questions — just keep the conversation going!`,
      `Task complete! I've analyzed your input and produced results via the A2A protocol. Would you like me to go deeper on any specific aspect?`,
      `Here's my response based on your query. I'm communicating over the Agent-to-Agent protocol, so multi-turn interactions are fully supported. What's next?`,
    );
  }

  // Pick response based on message content for variety
  const idx = (message.length + (agent.name || '').length) % matchedPools.length;
  return matchedPools[idx];
}

export default function ChatPlayground({ agent, endpointUrl }) {
  const greeting = `Hi! I'm the **${agent.name}**. ${agent.description} How can I help you today?`;
  const [messages, setMessages] = useState([{ role: 'assistant', content: greeting }]);
  const [input, setInput] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [endpoint, setEndpoint] = useState(endpointUrl || '');
  const [endpointInput, setEndpointInput] = useState(endpointUrl || '');
  const [connected, setConnected] = useState(false);
  const [agentCard, setAgentCard] = useState(null);
  const [connectionError, setConnectionError] = useState(null);
  const [sessionId] = useState(() => `session-${crypto.randomUUID()}`);
  const [taskId, setTaskId] = useState(null);
  const abortRef = useRef(null);
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  const isLive = connected && endpoint;

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages]);

  useEffect(() => {
    inputRef.current?.focus();
  }, []);

  // Reset when agent changes
  useEffect(() => {
    setMessages([{ role: 'assistant', content: greeting }]);
    setInput('');
    setIsTyping(false);
    setConnected(false);
    setAgentCard(null);
    setConnectionError(null);
    setTaskId(null);
    setEndpoint(endpointUrl || '');
    setEndpointInput(endpointUrl || '');
  }, [agent.id, agent.name, agent.description, endpointUrl, greeting]);

  const handleConnect = useCallback(async () => {
    const url = endpointInput.trim().replace(/\/+$/, '');
    if (!url) return;
    setConnectionError(null);
    try {
      const card = await fetchAgentCard(url);
      setAgentCard(card);
      setEndpoint(url);
      setConnected(true);
      setMessages((prev) => [
        ...prev,
        {
          role: 'system',
          content: `🟢 Connected to **${card.name || 'agent'}** at \`${url}\`${card.capabilities?.streaming ? ' (streaming enabled)' : ''}`,
        },
      ]);
    } catch (err) {
      setConnectionError(`Could not connect: ${err.message}`);
      setConnected(false);
    }
  }, [endpointInput]);

  const handleDisconnect = () => {
    setConnected(false);
    setAgentCard(null);
    setEndpoint('');
    setTaskId(null);
    setMessages((prev) => [...prev, { role: 'system', content: '🔴 Disconnected from live agent. Responses are now simulated.' }]);
  };

  const handleSend = useCallback(async () => {
    const trimmed = input.trim();
    if (!trimmed || isTyping) return;

    setMessages((prev) => [...prev, { role: 'user', content: trimmed }]);
    setInput('');
    setIsTyping(true);

    if (!isLive) {
      // Simulated fallback
      const delay = 800 + Math.random() * 1200;
      setTimeout(() => {
        const reply = getSimulatedReply(agent, trimmed);
        setMessages((prev) => [...prev, { role: 'assistant', content: reply }]);
        setIsTyping(false);
      }, delay);
      return;
    }

    // Real A2A call
    try {
      const supportsStreaming = agentCard?.capabilities?.streaming;

      if (supportsStreaming) {
        const controller = new AbortController();
        abortRef.current = controller;
        let fullText = '';
        let currentTaskId = taskId;

        // Add placeholder message that we'll update
        setMessages((prev) => [...prev, { role: 'assistant', content: '...' }]);

        for await (const event of streamMessage(endpoint, trimmed, sessionId, currentTaskId, controller.signal)) {
          if (event.id && !currentTaskId) {
            currentTaskId = event.id;
            setTaskId(event.id);
          }

          const chunk = extractText(event);
          if (chunk) {
            fullText = chunk; // A2A sends full text per update, not deltas
            setMessages((prev) => {
              const updated = [...prev];
              updated[updated.length - 1] = { role: 'assistant', content: fullText };
              return updated;
            });
          }

          // Handle input-required state
          if (event.status?.state === 'input-required') {
            const statusMsg = extractText(event);
            if (statusMsg) {
              setMessages((prev) => {
                const updated = [...prev];
                updated[updated.length - 1] = { role: 'assistant', content: statusMsg };
                return updated;
              });
            }
          }
        }

        // If we never got any content, show a status message
        if (!fullText) {
          setMessages((prev) => {
            const updated = [...prev];
            updated[updated.length - 1] = { role: 'assistant', content: '_Agent completed the task with no text output._' };
            return updated;
          });
        }
      } else {
        // Non-streaming: single request/response
        const result = await sendMessage(endpoint, trimmed, sessionId, taskId);
        if (result.id && !taskId) setTaskId(result.id);

        const text = extractText(result) || '_Agent completed the task with no text output._';
        setMessages((prev) => [...prev, { role: 'assistant', content: text }]);
      }
    } catch (err) {
      if (err.name === 'AbortError') return;
      setMessages((prev) => [
        ...prev,
        { role: 'system', content: `⚠️ Error: ${err.message}` },
      ]);
    } finally {
      setIsTyping(false);
      abortRef.current = null;
    }
  }, [input, isTyping, isLive, agent, agentCard, endpoint, sessionId, taskId]);

  const handleKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSend();
    }
  };

  const handleClear = () => {
    setMessages([{ role: 'assistant', content: greeting }]);
    setTaskId(null);
  };

  const handleStop = () => {
    if (abortRef.current) {
      abortRef.current.abort();
      setIsTyping(false);
    }
  };

  const renderContent = (text) => {
    // Simple markdown: bold, inline code, code blocks
    return text.split(/(\*\*.*?\*\*|`[^`]+`|```[\s\S]*?```)/g).map((part, i) => {
      if (part.startsWith('**') && part.endsWith('**')) {
        return <strong key={i}>{part.slice(2, -2)}</strong>;
      }
      if (part.startsWith('```') && part.endsWith('```')) {
        return <pre key={i} className="chat-code-block">{part.slice(3, -3).replace(/^\w*\n/, '')}</pre>;
      }
      if (part.startsWith('`') && part.endsWith('`')) {
        return <code key={i} className="chat-inline-code">{part.slice(1, -1)}</code>;
      }
      return part;
    });
  };

  return (
    <div className="chat-playground">
      <div className="chat-header-bar">
        <span className="chat-header-title">
          💬 Chat Playground
          {isLive && <span className="chat-live-badge">● LIVE</span>}
          {!isLive && <span className="chat-sim-badge">SIMULATED</span>}
        </span>
        <div className="chat-header-actions">
          {isTyping && isLive && (
            <button className="chat-stop-btn" onClick={handleStop} title="Stop generation">⏹</button>
          )}
          <button className="chat-clear-btn" onClick={handleClear} title="Clear chat">🗑️</button>
        </div>
      </div>

      {/* Endpoint connection bar */}
      <div className="chat-endpoint-bar">
        {!connected ? (
          <>
            <input
              className="chat-endpoint-input"
              type="text"
              value={endpointInput}
              onChange={(e) => setEndpointInput(e.target.value)}
              onKeyDown={(e) => e.key === 'Enter' && handleConnect()}
              placeholder="Enter A2A agent URL (e.g. /a2a-proxy/9999)"
            />
            <button className="chat-connect-btn" onClick={handleConnect} disabled={!endpointInput.trim()}>
              Connect
            </button>
          </>
        ) : (
          <div className="chat-connected-bar">
            <span className="chat-connected-label">🟢 {agentCard?.name || endpoint}</span>
            <button className="chat-disconnect-btn" onClick={handleDisconnect}>Disconnect</button>
          </div>
        )}
        {connectionError && <div className="chat-connection-error">{connectionError}</div>}
      </div>

      <div className="chat-messages">
        {messages.map((msg, i) => (
          <div key={i} className={`chat-message chat-message-${msg.role}`}>
            {msg.role === 'assistant' && (
              <span className="chat-avatar">{agent.icon}</span>
            )}
            {msg.role === 'system' && (
              <span className="chat-avatar">ℹ️</span>
            )}
            <div className={`chat-bubble chat-bubble-${msg.role}`}>
              {renderContent(msg.content)}
            </div>
          </div>
        ))}
        {isTyping && (
          <div className="chat-message chat-message-assistant">
            <span className="chat-avatar">{agent.icon}</span>
            <div className="chat-bubble chat-bubble-assistant chat-typing">
              <span className="typing-dot" />
              <span className="typing-dot" />
              <span className="typing-dot" />
            </div>
          </div>
        )}
        <div ref={messagesEndRef} />
      </div>

      <div className="chat-input-area">
        <textarea
          ref={inputRef}
          className="chat-input"
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder={isLive ? `Message ${agentCard?.name || agent.name}...` : `Ask ${agent.name} something (simulated)...`}
          rows={1}
          disabled={isTyping}
        />
        <button
          className="chat-send-btn"
          onClick={handleSend}
          disabled={!input.trim() || isTyping}
          title="Send message"
        >
          ➤
        </button>
      </div>

      <p className="chat-disclaimer">
        {isLive
          ? `Connected to live A2A agent at ${endpoint}`
          : 'Enter an A2A agent URL above to chat with a real agent, or send messages for simulated responses.'
        }
      </p>
    </div>
  );
}
