// Static data for the Relationship View — agents, models, and tools
// Agents sourced from https://github.com/a2aproject/a2a-samples

export const agents = [
  {
    id: 'a1',
    name: 'LangGraph Currency Agent',
    description: 'Converts currencies using tools with LangGraph. Multi-turn interactions, tool usage, and streaming.',
    icon: '🔗',
    color: '#059669',
    capabilities: ['Currency Conversion', 'Streaming', 'Multi-turn'],
    models: ['m1', 'm4'],
    tools: ['t1', 't5'],
  },
  {
    id: 'a2',
    name: 'Coder Agent (Genkit)',
    description: 'Generates code from natural language instructions with streaming file outputs. Built with Genkit.',
    icon: '💻',
    color: '#8b5cf6',
    capabilities: ['Code Generation', 'Streaming', 'File Output'],
    models: ['m4'],
    tools: ['t3', 't4', 't6'],
  },
  {
    id: 'a3',
    name: 'Enterprise Data Agent',
    description: 'Answers questions from any database, data warehouse, or app — powered by Gemini and MindsDB.',
    icon: '🗄️',
    color: '#14b8a6',
    capabilities: ['Database Querying', 'NL to SQL', 'Data Warehouse'],
    models: ['m4'],
    tools: ['t5', 't2'],
  },
  {
    id: 'a4',
    name: 'CrewAI Image Generator',
    description: 'Generates stunning images on demand using CrewAI, sending images through the A2A protocol.',
    icon: '🎨',
    color: '#c084fc',
    capabilities: ['Image Generation', 'Image Editing'],
    models: ['m4'],
    tools: ['t8'],
  },
  {
    id: 'a5',
    name: 'AI Agent (.NET Semantic Kernel)',
    description: 'Intelligent agent with summarization, sentiment analysis, translation, and idea generation.',
    icon: '🧠',
    color: '#4f46e5',
    capabilities: ['Summarization', 'Sentiment Analysis', 'Translation'],
    models: ['m1', 'm2'],
    tools: ['t1', 't2'],
  },
  {
    id: 'a6',
    name: 'GitHub Agent',
    description: 'Interacts with GitHub — manages issues, pull requests, and code reviews via A2A protocol.',
    icon: '🐙',
    color: '#1f2937',
    capabilities: ['Issue Management', 'Code Review', 'GitHub API'],
    models: ['m4'],
    tools: ['t6', 't3', 't4'],
  },
];

export const models = [
  {
    id: 'm1',
    name: 'GPT-4o',
    provider: 'OpenAI',
    description: 'Multimodal flagship model with strong reasoning, coding, and creative abilities.',
    icon: '🧠',
    color: '#10b981',
    type: 'Large Language Model',
    parameters: '~1.8T',
    context: '128K tokens',
  },
  {
    id: 'm2',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    description: 'High-performance model excelling at analysis, coding, and nuanced instructions.',
    icon: '🎭',
    color: '#14b8a6',
    type: 'Large Language Model',
    parameters: 'Undisclosed',
    context: '200K tokens',
  },
  {
    id: 'm3',
    name: 'Codex',
    provider: 'OpenAI',
    description: 'Specialized code generation model trained on vast repositories of source code.',
    icon: '⚙️',
    color: '#059669',
    type: 'Code Model',
    parameters: '~12B',
    context: '8K tokens',
  },
  {
    id: 'm4',
    name: 'Gemini Pro',
    provider: 'Google',
    description: 'Versatile model with strong multimodal, reasoning, and analytical capabilities.',
    icon: '💎',
    color: '#0d9488',
    type: 'Large Language Model',
    parameters: 'Undisclosed',
    context: '1M tokens',
  },
  {
    id: 'm5',
    name: 'LLaMA 3',
    provider: 'Meta',
    description: 'Open-source large language model with competitive performance across benchmarks.',
    icon: '🦙',
    color: '#047857',
    type: 'Open-Source LLM',
    parameters: '70B',
    context: '8K tokens',
  },
];

export const tools = [
  {
    id: 't1',
    name: 'Web Search',
    description: 'Searches the internet for real-time information and returns relevant results.',
    icon: '🌐',
    color: '#f59e0b',
    category: 'Information Retrieval',
  },
  {
    id: 't2',
    name: 'File Reader',
    description: 'Reads and parses files in various formats including PDF, CSV, JSON, and more.',
    icon: '📄',
    color: '#f97316',
    category: 'Data Processing',
  },
  {
    id: 't3',
    name: 'Code Executor',
    description: 'Runs code in sandboxed environments supporting Python, JavaScript, and more.',
    icon: '▶️',
    color: '#ef4444',
    category: 'Execution',
  },
  {
    id: 't4',
    name: 'Terminal',
    description: 'Executes shell commands and scripts in a controlled terminal environment.',
    icon: '🖥️',
    color: '#dc2626',
    category: 'Execution',
  },
  {
    id: 't5',
    name: 'Database Query',
    description: 'Connects to databases and executes SQL or NoSQL queries to retrieve data.',
    icon: '🗄️',
    color: '#d97706',
    category: 'Data Processing',
  },
  {
    id: 't6',
    name: 'Git Operations',
    description: 'Manages version control operations: commit, branch, merge, and repository management.',
    icon: '🔀',
    color: '#ea580c',
    category: 'DevOps',
  },
  {
    id: 't7',
    name: 'Chart Generator',
    description: 'Creates data visualizations including bar charts, line graphs, and dashboards.',
    icon: '📈',
    color: '#b45309',
    category: 'Visualization',
  },
  {
    id: 't8',
    name: 'Image Generator',
    description: 'Creates images from text descriptions using diffusion-based generative models.',
    icon: '🎨',
    color: '#c2410c',
    category: 'Creative',
  },
  {
    id: 't9',
    name: 'Cloud Deploy',
    description: 'Deploys applications to cloud providers like AWS, Azure, and GCP.',
    icon: '☁️',
    color: '#e11d48',
    category: 'DevOps',
  },
  {
    id: 't10',
    name: 'Browser Automation',
    description: 'Controls a headless browser for testing, scraping, and automated interactions.',
    icon: '🤖',
    color: '#be123c',
    category: 'Automation',
  },
];

// Helper to look up items by ID
export const getById = (collection, id) => collection.find((item) => item.id === id);
