// Data for agents, models, and tools

export const agents = [
  {
    id: 'a1',
    name: 'Research Agent',
    description: 'Gathers and synthesizes information from multiple sources to answer complex questions.',
    icon: '🔍',
    color: '#6366f1',
    capabilities: ['Web Search', 'Document Analysis', 'Summarization'],
    models: ['m1', 'm2'],
    tools: ['t1', 't2', 't5'],
  },
  {
    id: 'a2',
    name: 'Coding Agent',
    description: 'Writes, reviews, and debugs code across multiple programming languages and frameworks.',
    icon: '💻',
    color: '#8b5cf6',
    capabilities: ['Code Generation', 'Bug Fixing', 'Refactoring'],
    models: ['m1', 'm3'],
    tools: ['t3', 't4', 't6'],
  },
  {
    id: 'a3',
    name: 'Data Analyst',
    description: 'Processes datasets, generates visualizations, and extracts meaningful insights.',
    icon: '📊',
    color: '#a855f7',
    capabilities: ['Data Processing', 'Visualization', 'Statistical Analysis'],
    models: ['m2', 'm4'],
    tools: ['t2', 't5', 't7'],
  },
  {
    id: 'a4',
    name: 'Creative Writer',
    description: 'Generates compelling content including articles, stories, marketing copy, and more.',
    icon: '✍️',
    color: '#c084fc',
    capabilities: ['Content Creation', 'Editing', 'Style Adaptation'],
    models: ['m1', 'm5'],
    tools: ['t1', 't8'],
  },
  {
    id: 'a5',
    name: 'DevOps Agent',
    description: 'Manages CI/CD pipelines, infrastructure provisioning, and deployment automation.',
    icon: '🚀',
    color: '#7c3aed',
    capabilities: ['Deployment', 'Monitoring', 'Infrastructure as Code'],
    models: ['m3', 'm4'],
    tools: ['t3', 't4', 't6', 't9'],
  },
  {
    id: 'a6',
    name: 'QA Agent',
    description: 'Tests software, identifies edge cases, and validates functionality against requirements.',
    icon: '🧪',
    color: '#5b21b6',
    capabilities: ['Test Generation', 'Bug Reporting', 'Regression Testing'],
    models: ['m2', 'm3'],
    tools: ['t3', 't4', 't10'],
  },
];

export const models = [
  {
    id: 'm1',
    name: 'GPT-4o',
    provider: 'OpenAI',
    description: 'Multimodal flagship model with strong reasoning, coding, and creative abilities.',
    icon: '🧠',
    color: '#10b981',
    type: 'Large Language Model',
    parameters: '~1.8T',
    context: '128K tokens',
  },
  {
    id: 'm2',
    name: 'Claude 3.5 Sonnet',
    provider: 'Anthropic',
    description: 'High-performance model excelling at analysis, coding, and nuanced instructions.',
    icon: '🎭',
    color: '#14b8a6',
    type: 'Large Language Model',
    parameters: 'Undisclosed',
    context: '200K tokens',
  },
  {
    id: 'm3',
    name: 'Codex',
    provider: 'OpenAI',
    description: 'Specialized code generation model trained on vast repositories of source code.',
    icon: '⚙️',
    color: '#059669',
    type: 'Code Model',
    parameters: '~12B',
    context: '8K tokens',
  },
  {
    id: 'm4',
    name: 'Gemini Pro',
    provider: 'Google',
    description: 'Versatile model with strong multimodal, reasoning, and analytical capabilities.',
    icon: '💎',
    color: '#0d9488',
    type: 'Large Language Model',
    parameters: 'Undisclosed',
    context: '1M tokens',
  },
  {
    id: 'm5',
    name: 'LLaMA 3',
    provider: 'Meta',
    description: 'Open-source large language model with competitive performance across benchmarks.',
    icon: '🦙',
    color: '#047857',
    type: 'Open-Source LLM',
    parameters: '70B',
    context: '8K tokens',
  },
];

export const tools = [
  {
    id: 't1',
    name: 'Web Search',
    description: 'Searches the internet for real-time information and returns relevant results.',
    icon: '🌐',
    color: '#f59e0b',
    category: 'Information Retrieval',
  },
  {
    id: 't2',
    name: 'File Reader',
    description: 'Reads and parses files in various formats including PDF, CSV, JSON, and more.',
    icon: '📄',
    color: '#f97316',
    category: 'Data Processing',
  },
  {
    id: 't3',
    name: 'Code Executor',
    description: 'Runs code in sandboxed environments supporting Python, JavaScript, and more.',
    icon: '▶️',
    color: '#ef4444',
    category: 'Execution',
  },
  {
    id: 't4',
    name: 'Terminal',
    description: 'Executes shell commands and scripts in a controlled terminal environment.',
    icon: '🖥️',
    color: '#dc2626',
    category: 'Execution',
  },
  {
    id: 't5',
    name: 'Database Query',
    description: 'Connects to databases and executes SQL or NoSQL queries to retrieve data.',
    icon: '🗄️',
    color: '#d97706',
    category: 'Data Processing',
  },
  {
    id: 't6',
    name: 'Git Operations',
    description: 'Manages version control operations: commit, branch, merge, and repository management.',
    icon: '🔀',
    color: '#ea580c',
    category: 'DevOps',
  },
  {
    id: 't7',
    name: 'Chart Generator',
    description: 'Creates data visualizations including bar charts, line graphs, and dashboards.',
    icon: '📈',
    color: '#b45309',
    category: 'Visualization',
  },
  {
    id: 't8',
    name: 'Image Generator',
    description: 'Creates images from text descriptions using diffusion-based generative models.',
    icon: '🎨',
    color: '#c2410c',
    category: 'Creative',
  },
  {
    id: 't9',
    name: 'Cloud Deploy',
    description: 'Deploys applications to cloud providers like AWS, Azure, and GCP.',
    icon: '☁️',
    color: '#e11d48',
    category: 'DevOps',
  },
  {
    id: 't10',
    name: 'Browser Automation',
    description: 'Controls a headless browser for testing, scraping, and automated interactions.',
    icon: '🤖',
    color: '#be123c',
    category: 'Automation',
  },
];

// Helper to look up items by ID
export const getById = (collection, id) => collection.find((item) => item.id === id);
